ALTER TABLE `user` ADD COLUMN `first_Name` VARCHAR(255);
ALTER TABLE `user` ADD COLUMN `last_Name` VARCHAR(255);
ALTER TABLE `user` ADD COLUMN `email` VARCHAR(255);
ALTER TABLE `user` ADD COLUMN `phone` VARCHAR(255);


ALTER TABLE `address` ADD COLUMN `ulica` VARCHAR(255);
ALTER TABLE `address` ADD COLUMN `nr_ulicy` VARCHAR(255);
ALTER TABLE `address` ADD COLUMN `post_Code` VARCHAR(255);
ALTER TABLE `address` ADD COLUMN `miasto` VARCHAR(255);
ALTER TABLE `address` ADD COLUMN `user_id` BIGINT(20)NOT NULL;
