server:
  port: 5000

spring:
  application:
    name: ProxyService

eureka:
  instance:
    prefer-ip-address: true
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.int}}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.int}}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

zuul:
  prefix: /api
  routes:
    MicroserviceA:
      path: /MicroA/**
      serviceId: Microservice-A
      sensitiveHeaders:
    MicroserviceB:
      path: /MicroB/**
      serviceId: Microservice-B
      sensitiveHeaders:
