server:
  port: 0

spring:
  application:
    name: Microservice-A
  datasource:
    username: root
    password: fdgjyraFESCnte
    url: jdbc:mysql://54.38.187.126:3310/tomson
  jpa:
    properties:
      hibernate:
        id:
          new_generator_mappings: false

eureka:
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.int}}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka