server:
  port: 8555

spring:
  application:
    name: Microservice-A
  datasource:
    username: tomson
    password: T0ms0n2019
    url: jdbc:mysql://192.168.99.100:3310/tomson
  jpa:
    properties:
      hibernate:
        id:
          new_generator_mappings: false

eureka:
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.int}}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
tomson:
  google:
    project:
      id: spring-server

---
spring:
  profiles: docker

eureka:
  client:
     serviceUrl:
       defaultZone: http://192.168.1.73:8761/eureka

